#!/bin/bash -e

for i in {0..255} ; do
    printf "\x1b[48;5;%sm%3d\e[0m " "$i" "$i"
    if (( i == 15 )) || (( i > 15 )) && (( (i-15) % 6 == 0 )); then
        printf "\n";
    fi
done

# To print out a colour in zsh you can do:
# print -P '%F{214}%K{123}%m%k%f'
# Where F/f set/unset the foreground colour (here to 214) and K/k the
# background.
