#!/bin/sh

# Calls scripts from setup/ if the OS matches.

. $(dirname $0)/helpers/setup.sh # Load helper script from dot/helpers.

# Enable hardcore mode if you're sure.
read -p "HARDCORE mode (leave blank not to enable)? " HARDCORE
export HARDCORE

echo "❯❯❯ HARDCORE mode $([ "$HARDCORE" ] && echo on || echo off)"
[ "$HARDCORE" ] && sleep 3 # Give people a chance to see (or Control-C).

# Good defaults:
[ -z "$XDG_CONFIG_HOME" ] && export XDG_CONFIG_HOME="$HOME/.config"
[ -z "$XDG_CACHE_HOME" ] && export XDG_CACHE_HOME="$HOME/.cache"
[ -z "$XDG_DATA_HOME" ] && export XDG_DATA_HOME="$HOME/.local/share"

# Setup dotfile symlinks.
./rcme

# Platform specific setup:
if [ "$(uname)" = Darwin ]; then # macOS
  $(dirname $0)/setup/mac.sh
elif [ "$(uname)" = Linux ]; then # Linux specific stuff.
  case "$(uname -v)" in
    *Ubuntu* | *ubuntu*) # Ubuntu specific setup.
      $(dirname $0)/setup/ubu.sh ;;
    *) echo "No specific setup files for $(uname -v) yet" ;;
  esac
fi

# Cross-platform setup:
./setup/unix.sh
