#!/bin/bash

. "$(dirname "$0")"/../../helpers/setup.sh # Load helper script from dot/helpers.

set -eux

# Don't run if user is not gib.
[[ ! $USER == gib ]] && exit 1

changes=$(gitCloneOrUpdate fwcd/KotlinLanguageServer "$XDG_DATA_HOME/KotlinLanguageServer")

log_info "$changes"

[[ -n $changes ]] || exit 204 # Run if there were changes.
