#!/usr/bin/env bash

set -eu

[[ $(uname) != Darwin ]] && exit 1 # Don't run if not Darwin.

fixed="# sudo: auth account password session
auth       sufficient     pam_tid.so
auth       sufficient     pam_smartcard.so
auth       required       pam_opendirectory.so
account    required       pam_permit.so
password   required       pam_deny.so
session    required       pam_permit.so"

current=$(</etc/pam.d/sudo)

echo -e "Contents of /etc/pam.d/sudo:

Actual:
---$current---

Expected (if fixed already):
+++$fixed+++" >&2

# Run if /etc/pam.d/sudo is not already the fixed version.
[[ "$current" != "$fixed" ]]
