#!/usr/bin/env bash

set -eux

[[ $(uname) == Darwin ]] || exit 1

[[ -e /var/db/locate.database ]] || exit 1

# Run if the db is less than an hour old.
((($(date +%s) - $(stat -L -f '%m' /var/db/locate.database)) > (1 * 60 * 60)))
