# Basic things I'd install on any machine.

# Bootstrapping.

brew "watch"                             # Rerun a command every n seconds.
brew "pstree"                            # Hierarchical tree of processes, `pstree -g 3`.

cask "kitty"                             # GPU Accelerated cross-platform Terminal Emulator.
cask "font-hasklig"                      # Nice programming font Hasklig (Source Code Pro + Ligatures).
cask "font-hasklug-nerd-font"            # Nice programming font Hasklig (Source Code Pro + Ligatures) + Nerd Font extensions.
cask "hammerspoon"                       # Scriptable automator for macOS.
cask "maccy"                             # Clipboard manager with history.
brew "neovim"                            # New and improved vim.

cask "1password"                         # Password manager, installed first so I can log into things.
brew "gnupg"                             # gpg command line.
brew "gh"                                # GitHub CLI.

# Brew formulae

brew "bash"                              # macOS Bash is very old.
brew "coreutils"                         # GNU versions of utils that are out-of-date or FreeBSD on macOS (inc dircolors).
brew "expect"                            # Includes `unbuffer` for making programs think stdout/stderr is a tty.
brew "fd"                                # Super-fast find replacement.
brew "fzf"                               # Fuzzy file finder.
brew "git"                               # Bleeding-edge git.
brew "git-delta"                         # Nicer git diff viewer.
brew "gnu-sed"                           # A sed that actually supports `sed -i`.
brew "htop"                              # Terminal activity monitor.
brew "less"                              # Fixes -RX issue.
brew "mas"                               # Mac App Store third-party cli.
brew "node"                              # Node.js programming language.
brew "pinentry-mac"                      # Gpg password Keychain integration.
brew "python"                            # Python 3
brew "ripgrep"                           # Super-fast version of grep.
brew "tree"                              # Recursive ls.
brew "volta"                             # Node version manager.
brew "watchexec"                         # Run commands when files change.
brew "zoxide"                            # Z (for changing directory) but in Rust.
brew "zsh"                               # Nicer interactive shell.

# Brew casks (GUI Applications):

# cask "vlc"                               # Nice video player.
cask "google-chrome"                     # You probably want/have Chrome.
cask "keyboard-cleaner"                  # Block all keystrokes except ⌘-q so you can wipe your keyboard.
cask "spotify"                           # Music.
cask "time-out"                          # Reminds you to take breaks.
cask "wechat"                            # Chinese chat client.
cask "whatsapp"                          # Whatsapp client.
cask "workflowy"                         # Infinitely nested bullet point list app.
