#!/usr/bin/env bash

set -euo pipefail

# Ensure `git maintenance` CRON is set up.
# <https://git-scm.com/docs/git-maintenance>
for f in org.git-scm.git.daily.plist org.git-scm.git.hourly.plist org.git-scm.git.weekly.plist; do
  if [[ ! -f ~/Library/LaunchAgents/$f ]]; then
    git -C "${dot_dir}" maintenance start
    break
  fi
done

# Create maintenance files if not present.
config_file=~/.config/git/maintenance.config
if [[ ! -f $config_file ]]; then
  echo "[maintenance]" >"$config_file"
fi

# Run commands that act on each repo.
GIT_EACH_DIRS="$HOME/wrk
$HOME/code
${XDG_DATA_HOME}/zsh/plugins
${XDG_DATA_HOME}/hammerspoon
" "${dot_dir}"/dotfiles/bin/git-each "${dot_dir}"/scripts/run/git-each-repo

# Delete repos that are no longer present.
for repo in $(awk '$1 == "repo" { print $3 }' "$config_file"); do
  if [[ ! -e $repo/.git ]]; then
    sed -i.bak "\\:$repo:d" "$config_file"
    rm "$config_file".bak
  fi
done
