#!/usr/bin/env bash

set -euxo pipefail

work_done=

# Use the default location so less finds this by default.
lesskey_file=$XDG_CONFIG_HOME/lesskey

# If the old file is still around, remove it.
if [[ -f $XDG_CACHE_HOME/less ]]; then
  rm "$XDG_CACHE_HOME/less"
  work_done=true
fi

current=$(md5 -q "$lesskey_file" 2>/dev/null || true)

# Build the lesskey source (colors for less).
# Since less 582 the lesskey source file is read directly, so we no longer run lesskey to convert it
# to a binary file. We don't commit this file because we need the machine's terminal to resolve the
# tput commands.
lesskey_source=$(
  cat <<EOF
#env

LESS_TERMCAP_ZN = $(tput ssubm)
LESS_TERMCAP_ZO = $(tput ssupm)
LESS_TERMCAP_ZV = $(tput rsubm)
LESS_TERMCAP_ZW = $(tput rsupm)
# green
LESS_TERMCAP_mb = $(
    tput bold
    tput setaf 2
  )
# Blue.
LESS_TERMCAP_md = $(
    tput bold
    tput setaf 74
  )
# Reset (turn everything off).
LESS_TERMCAP_me = $(tput sgr0)
# Dim (half-bright) mode.
LESS_TERMCAP_mh = $(tput dim)
# Reverse mode.
LESS_TERMCAP_mr = $(tput rev)
# End standout-mode.
LESS_TERMCAP_se = $(
    tput rmso
    tput sgr0
  )
# Begin standout-mode - info box (yellow on blue).
LESS_TERMCAP_so = $(
    tput bold
    tput setaf 3
    tput setab 4
  )
 # End underline.
LESS_TERMCAP_ue = $(
    tput rmul
    tput sgr0
  )
# Begin underline (white).
LESS_TERMCAP_us = $(
    tput smul
    tput bold
    tput setaf 146
  )
EOF
)

# Only write the file if it's missing or its contents have changed.
if [[ "$current" != "$(md5 -q <<<"$lesskey_source")" ]]; then
  printf '%s\n' "$lesskey_source" >"$lesskey_file"
  work_done=true
fi

if [[ -z $work_done ]]; then
  exit "$UP_EXIT_CODE_SKIPPED"
fi
