#!/usr/bin/env zsh

set -euo pipefail

EXIT_CODE_SKIPPED=204 # up treats this exit code as "skipped"

set -x

# OS is darwin or we don't run.
[[ $OSTYPE == darwin* ]] || exit "$EXIT_CODE_SKIPPED"

loginwindow_prefs=~/Library/Preferences/ByHost/com.apple.loginwindow*

# If we can't find the file, we probably already nuked the preferences.
if [[ ! -f $loginwindow_prefs ]]; then
  exit "$EXIT_CODE_SKIPPED"
fi

sudo chown root ~/Library/Preferences/ByHost/com.apple.loginwindow*

sudo chmod 000 ~/Library/Preferences/ByHost/com.apple.loginwindow*
