#!/bin/bash

# The equivalent of:
#
# ```
# sudo tee /etc/pam.d/sudo_local <<<"auth       sufficient     pam_tid.so" >/dev/null
# ```
#
# Copies what's in /etc/pam.d/sudo_local.template

set -euo pipefail

[[ $OSTYPE == darwin* ]] || exit 204 # Don't run if not Darwin.

pamd_local_path=/etc/pam.d/sudo_local
sudo_local_touch_id_line="auth       sufficient     pam_tid.so"

main() {
  # Use work override script if present.
  if [[ -d ${wrk_dot_dir:-} ]] && command -v liv &>/dev/null; then
    "$wrk_dot_dir"/scripts/run/touchid_sudo
    exit
  fi

  if [[ ! -f $pamd_local_path ]]; then
    echo >&2 "Adding Touch ID sudo line to ${pamd_local_path}"
    sudo tee "$pamd_local_path" <<<"${sudo_local_touch_id_line}" >/dev/null
  elif grep -Fx "$sudo_local_touch_id_line" "$pamd_local_path" >/dev/null; then
    echo >&2 "Touch ID line already present in ${pamd_local_path}, skipping..."
    exit 204
  else
    echo >&2 "ERROR: Unexpected contents of $pamd_local_path}"
    exit 9
  fi

}

main "$@"
