#!/usr/bin/env bash

set -euo pipefail

set -x

# Update lazy.nvim plugins, then TreeSitter plugins, then Mason dependencies.
nvim \
  --headless \
  -c "Lazy! sync" \
  -c 'lua require("nvim-treesitter").update():wait(300000)' \
  -c 'autocmd User MasonUpdateAllComplete quitall' \
  -c 'MasonUpdateAll'

# Work around https://github.com/Maxattax97/coc-ccls/issues/2
existing=~/.config/coc/extensions/node_modules/coc-ccls/node_modules/ws/lib/extension.js
missing=~/.config/coc/extensions/node_modules/coc-ccls/lib/extension.js
if [[ -e "$existing" && ! -e "$missing" ]]; then
  mkdir -p "$(dirname "$missing")"
  ln -s "$existing" "$missing"
fi

if [[ ${USER:-} != gib ]]; then
  exit
fi

# Remove any leftovers from the old way of doing things.
[[ -L ~/bin/nvim ]] && rm ~/bin/nvim
old_nightly_dir="${XDG_DATA_HOME:-$HOME/.local/share}"/nvim-nightly
[[ -d "$old_nightly_dir" ]] && rm -rf "$old_nightly_dir"

bob_bin_dir="${XDG_DATA_HOME:-$HOME/.local/share}"/bob/nvim-bin

if [[ -f ~/.netrc ]]; then
  { set +x; } 2>/dev/null
  export GITHUB_TOKEN
  GITHUB_TOKEN=$(grep -xA 2 'machine github.com' ~/.netrc | awk '{ if ($1 == "password") { print $2 } }')
  set -x
fi

if [[ ! -d "$bob_bin_dir" ]]; then
  bob use nightly
  bob install stable
else
  bob update --all
fi
