#!/usr/bin/env bash

# Set lock screen and desktop backgrounds.

# Env:
#  - MAC_DESKTOP_BACKGROUND: local path to png to use as background.
#  - MAC_CLOUD_DESKTOP_BACKGROUND: cloud file to copy to local path before using.

set -e

. "$(dirname "$0")/../../helpers/setup.sh" # Load helper script from dot/helpers.

if [[ ! -e ${MAC_CLOUD_DESKTOP_BACKGROUND?} ]]; then
  brctl download "$MAC_CLOUD_DESKTOP_BACKGROUND"
fi
if [[ ! -e ${MAC_DESKTOP_BACKGROUND?} ]]; then
  cp "$MAC_CLOUD_DESKTOP_BACKGROUND" "$MAC_DESKTOP_BACKGROUND"
fi

# Set desktop background.
if osascript -e '
    tell application "System Events"
        tell every desktop
            get picture
        end tell
    end tell' | tr ',' '\n' | grep -v "$MAC_DESKTOP_BACKGROUND"; then

  log_get "Setting desktop background to $MAC_DESKTOP_BACKGROUND"
  osascript -e "
    tell application \"System Events\"
        tell every desktop
            set picture to \"$MAC_DESKTOP_BACKGROUND\"
        end tell
    end tell"
else
  log_skip "Setting desktop background to $MAC_DESKTOP_BACKGROUND"
fi
