#!/usr/bin/env zsh

set -euxo pipefail

# Ensure well-known directories are in the zoxide list of known directories.

setopt null_glob # Ignore globs that don't match anything.

# Zoxide should ignore inputs that don't exist, so put lots of things here.
to_add=(
  /opt/homebrew/Library/Taps/*/ # Brew tap groups.
  /opt/homebrew/Library/Taps/*/*/ # Brew taps.
  /private/var/tmp
  ~/.local/share/nvim/lazy/*/    # Neovim plugins.
  ~/.local/share/zsh/plugins/*/  # Zsh plugins.
  ~/.ssh/                        # SSH configs.
  ~/Library/Caches/*{gib,fahn}*/ # Caches for my tools.
  ~/Library/Logs/*{gib,fahn}*/   # Logs for my tools.
  ~/tmp/*/                       # My temporary subdirectories.
)

# Don't increment the score if already present.
zoxide add --score 0.0 "${to_add[@]}"
