#!/bin/bash

if command -v rg >/dev/null; then
  whoami=$(whoami)
  color_setting=--color=always
  [[ -n $MYVIMRC ]] && color_setting=
  # shellcheck disable=2086 # I want the color setting to expand to nothing.
  if matches=$(rg $color_setting --hidden --no-ignore --glob=!.git -F "XXX($whoami):"); then
    if [[ -z $MYVIMRC ]]; then
      RED='\033[0;31m' # Red.
      NC='\033[0m'     # No Colour.
    fi
    printf "${RED:-}ERROR:${NC:-} found XXX. To view these in Vim:
    v -q <(rga -F \"XXX(%s):\" --vimgrep)

%s" "$whoami" "$matches"
    exit 1
  fi
fi
