#!/bin/sh

set -eux

which gpg || exit "$UP_EXIT_CODE_SKIPPED"

# Run if gpg home missing, or gpg agent conf doesn't contain the expected values.
if [ -d "$GNUPGHOME" ] && grep -q 'pinentry-program .*/pinentry-mac' "$GNUPGHOME"/gpg-agent.conf; then
  exit "$UP_EXIT_CODE_SKIPPED"
fi
