#!/bin/sh

set -eux

EXIT_CODE_SKIPPED=204 # up treats this exit code as "skipped"

[ "$(uname)" = Darwin ] || exit "$EXIT_CODE_SKIPPED"
[ "$(whoami)" = gib ] || exit "$EXIT_CODE_SKIPPED"

# Run if the desktop background is not already the one we set.
backgrounds="$(osascript -e '
    tell application "System Events"
        tell every desktop
            get picture
        end tell
      end tell' | tr ',' '\n')"

[ -z "$backgrounds" ] && exit 1

echo "$backgrounds" | grep "$MAC_DESKTOP_BACKGROUND" && exit "$EXIT_CODE_SKIPPED" || exit 0
