#!/bin/sh

set -eux

[ "$(uname)" = Darwin ] || exit 204
[ "$(whoami)" = gib ] || exit 204

# Run if the desktop background is not already the one we set.
backgrounds="$(osascript -e '
    tell application "System Events"
        tell every desktop
            get picture
        end tell
      end tell' | tr ',' '\n')"

[ -z "$backgrounds" ] && exit 1

echo "$backgrounds" | grep "$MAC_DESKTOP_BACKGROUND" && exit 204 || exit 0
