# Basic things I'd install on any machine.

tap "homebrew/cask"                      # `brew cask` for GUI apps.
tap "homebrew/cask-fonts"                # Let's you `brew cask install` fonts.
tap "homebrew/bundle"                    # Allows you to use Brewfiles.
tap "homebrew/cask-versions"             # Allows installing other versions of casks.

# Versions of utils that are out-of-date on macOS:
# Defaults are in /usr/bin, brew installs to /usr/local/bin

brew "bash"                              # macOS Bash is very old.
brew "entr"                              # Command line file watching.
brew "fd"                                # Super-fast find replacement.
brew "git"                               # Bleeding-edge git.
brew "git-delta"                         # Nicer git diff viewer.
brew "gnu-sed"                           # A sed that actually supports `sed -i`.
brew "gnupg"                             # gpg command line.
brew "htop"                              # Terminal activity monitor.
brew "less"                              # Fixes -RX issue.
brew "mas"                               # Mac App Store third-party cli.
brew "neovim"                            # New and improved vim.
brew "pinentry-mac"                      # Gpg password Keychain integration.
brew "python"                            # Python 3
brew "ripgrep"                           # Super-fast version of grep.
brew "rmtrash"                           # `rm` to Trash, aliased to `dl` in gibrc.
brew "terminal-notifier"                 # Log notifications from the terminal.
brew "tree"                              # Recursive ls.
brew "zsh"                               # Nicer interactive shell.

# Casks (GUI Applications):

# cask "rectangle"                         # Window manager that's easy to get used to.
cask "1password"                         # Password manager.
cask "copyq"                             # Clipboard manager with history (needs manual setup).
cask "font-hasklig"                      # Nicer programming font option 2.
cask "google-chrome"                     # You probably want/have Chrome.
cask "karabiner-elements"                # Key remapper (see $c/karabiner/karabiner.json for my settings).
cask "keyboard-cleaner"                  # Block all keystrokes except ⌘-q so you can wipe your keyboard.
cask "kitty"                             # GPU Accelerated cross-platform Terminal Emulator.
cask "sogouinput"                        # Nicer Chinese input experience.
cask "spectacle"                         # Window manager that's easy to get used to.
cask "spotify"                           # Music.
cask "time-out"                          # Reminds you to take breaks.
cask "workflowy"                         # Infinitely nested bullet point list app.

mas "Pages", id: 409201541               # Edit docx and pages files.
mas "Runcat", id: 1429033973             # Show CPU usage in menu bar.
