run_lib = "git"

[[data]]
path = "~/code/dot"
remotes = [
  { name = "up", push = "https://github.com/gibfahn/dot", fetch = "git@github.com:gibfahn/dot" }
]

[[data]]
path = "~/code/dot"
  [[data.remotes]]
  name = "up"
  push_url = "https://github.com/gibfahn/dot"
  fetch_url = "git@github.com:gibfahn/dot"
