#!/usr/bin/env bash

set -eu

# Ensure `git maintenance` CRON is set up.
# <https://git-scm.com/docs/git-maintenance>
for f in org.git-scm.git.daily.plist org.git-scm.git.hourly.plist org.git-scm.git.weekly.plist; do
  if [[ ! -f ~/Library/LaunchAgents/$f ]]; then
    git -C "${dot_dir}" maintenance start
    break
  fi
done

# Create maintenance files if not present.
for config_file in ~/.config/git/maintenance-wrk.config ~/.config/git/maintenance.config; do
  if [[ ! -f $config_file ]]; then
    echo "[maintenance]" >"$config_file"
  fi
done

# Run commands that act on each repo.
"${dot_dir}"/dotfiles/bin/git-each "${dot_dir}"/up/run/git-each-repo

# Delete repos that are no longer present.
for config_file in ~/.config/git/maintenance-wrk.config ~/.config/git/maintenance.config; do
  for repo in $(awk '$1 == "repo" { print $3 }' "$config_file"); do
    if [[ ! -e $repo/.git ]]; then
      sed -i.bak "\\:$repo:d" "$config_file"
      rm "$config_file".bak
    fi
  done
done
