#!/usr/bin/env bash

set -eu

# Things that I want to do to every git repository, every time.

# If a repo isn't in $_ZL_DATA then add it.
if ! grep -q "^$PWD|" "$_ZL_DATA"; then
  echo >&2 "z.lua: adding $PWD to $_ZL_DATA"
  echo "$PWD|10|$(date +%s)" >>"$_ZL_DATA"
fi
