#!/usr/bin/env bash

set -euo pipefail

. "$(dirname "$0")"/../../helpers/setup.sh # Load helper script from dot/helpers.

set -x

# Don't run if user is not gib.
[[ $USER == gib ]] || exit 204

changes=$(gitCloneOrUpdate fwcd/KotlinLanguageServer "$XDG_DATA_HOME/KotlinLanguageServer")

log_info "$changes"

[[ -n $changes ]] || exit 204 # Run if there were changes.

cd "$XDG_DATA_HOME/KotlinLanguageServer"
./gradlew installDist # If tests passed we could use `./gradlew build`
ln -sf "$XDG_DATA_HOME/KotlinLanguageServer/server/build/install/server/bin/kotlin-language-server" "$HOME/bin/kotlin-language-server"
