#!/usr/bin/env bash

. "$(dirname "$0")"/../../helpers/setup.sh # Load helper script from dot/helpers.

set -eux

cd "$XDG_DATA_HOME/KotlinLanguageServer"
./gradlew installDist # If tests passed we could use `./gradlew build`
ln -sf "$XDG_DATA_HOME/KotlinLanguageServer/server/build/install/server/bin/kotlin-language-server" "$HOME/bin/kotlin-language-server"
