#!/usr/bin/env zsh

set -euo pipefail

# OS is darwin or we don't run.
[[ $1 == --run-if && $OSTYPE == darwin* ]] && exit 1

# Login Items that should be added to System Preferences -> Users & Groups -> Login Items
required_login_items=(
  /Applications/Rectangle.app
  /Applications/CopyQ.app
  /Applications/Hammerspoon.app
  /Applications/Time Out.app
  /Applications/Dato.app
)

# Set up login items.
IFS=$'\n' current_login_items=($(osascript -e 'tell application "System Events" to get login items' | sed -e 's/login item //g' -e 's/, /\n/g'))
for item_path in "${required_login_items[@]}"; do
  item=$(basename "${item_path%.app}")
  if ! (( ${current_login_items[(I)$item]} )); then
    if [[ $1 == --run-if ]]; then
      exit 0 # We need to change something, so should run.
    else
      echo "Adding login item $item" >&2
      osascript -e "tell application \"System Events\" to make login item at end with properties {path:\"$item_path\", hidden:false}"
    fi
  fi
done

# We didn't need to change anything, so exit 1 to not run.
[[ $1 == --run-if ]] && exit 1
