#!/usr/bin/env zsh

set -euo pipefail

# OS is darwin or we don't run.
[[ $OSTYPE == darwin* ]] || exit 204

changed=

# Set up login items.
IFS=$'\n' current_login_items=($(osascript -e 'tell application "System Events" to get login items' | sed -e 's/login item //g' -e 's/, /\n/g'))
for item_path in "${@}"; do
  item=$(basename "${item_path%.app}")
  if ! (( ${current_login_items[(I)$item]} )); then
    changed=true
    echo "Adding login item $item" >&2
    osascript -e "tell application \"System Events\" to make login item at end with properties {path:\"$item_path\", hidden:false}"
  fi
done

# If we didn't change anything, mark the task as skipped.
[[ -n changed ]] || exit 204
