#!/usr/bin/env zsh
# shellcheck shell=bash disable=SC1090,SC2016

# Things I like to have on a Mac.

set -euo pipefail

. "$(dirname "$0")/../../helpers/setup.sh" # Load helper script from dot/helpers.

main() {
  # Link VS Code preferences into the macOS specific folder.
  if [[ $USER == gib && -d "$HOME/Library/Application Support/Code/" ]]; then
    for file in "$HOME"/.config/code/*.json; do
      ln -sf "$file" "$HOME/Library/Application Support/Code/User/$(basename "$file")"
    done
  fi

  if [[ $USER == gib ]]; then # Set keyboard preferences.
    log_section "Setting gib extra macOS defaults."

    # Disable the macOS chime sound when you power on the machine.
    # On is %00, off is %01.
    if startup_mute=$(nvram StartupMute | awk '{print $NF}') && [[ $startup_mute == %01 ]]; then
      log_skip "macOS Startup Chime already disabled."
    else
      log_get "Disabling macOS Startup Chime"
      sudo nvram StartupMute=%01
    fi
  fi

  # Apply any changes made above:

  # Increase max file watch limit. See https://eradman.com/entrproject/limits.html
  # File downloaded from: https://eradman.com/entrproject/etc/limit.maxfiles.plist
  if [[ -e /Library/LaunchDaemons/limit.maxfiles.plist ]]; then
    log_skip "File watcher limit (already increased)."
  else
    log_get "File watcher limit."
    sudo cp "$(dirname "$0")"/../config/limit.maxfiles.plist /Library/LaunchDaemons/limit.maxfiles.plist
  fi

  # Remove any accidentally added Shared-Data links. They should all go via the symlink.
  log_get "Removing shared-data links"
  zoxide query --list | { grep Shared-Data || true; } | xargs -t zoxide remove

  echo "All done"
}

# Used when you're starting a new section.
log_section() {
  printf "❯❯❯ %s\n" "$@" 1>&2
}

main "$@"
