#!/usr/bin/env bash

. "$(dirname "$0")"/../../helpers/setup.sh # Load helper script from dot/helpers.

set -ex

npm_modules=(
  bash-language-server              # Language server for bash and other shell script files.
  diagnostic-languageserver         # Generic language server (see linters).
  dockerfile-language-server-nodejs # Language server for Dockerfiles.
  javascript-typescript-langserver  # Language server for JavaScript and Typescript files.
  neovim                            # Neovim plugin.
  write-good                        # English text linter.
  yarn                              # Alternative to npm.
)

# Install npm modules.
if [[ $USER == gib ]]; then
  installed_npm_module_versions="$(npm ls -g --depth=0 --loglevel=error | grep -Ex '.* [-_A-Za-z0-9]+@([0-9]+\.){2}[0-9]+' | sed -E 's/^.+ //' | sed 's/@/ /')"
  for module in "${npm_modules[@]}"; do
    if ! echo "$installed_npm_module_versions" | grep -qx "$module .*" \
      || [[ "$(echo "$installed_npm_module_versions" | grep -x "$module .*" | awk '{print $NF}')" != "$(npm info --loglevel=error "$module" version)" ]]; then
      log_get "npm: $module"
      npm install --global --loglevel=error "$module"@latest
    else
      log_skip "npm: $module"
    fi
  done
fi
