#!/usr/bin/env bash

set -euo pipefail

set -x

[[ -L ~/bin/nvim ]] || exit 204 # Skip if we're not using nvim nightly.

nightly_dir="${XDG_DATA_HOME:-$HOME/.local/share}"/nvim-nightly
mkdir -p "$nightly_dir"

# To use this run:
#   ln -sf ~/.local/share/nvim-nightly/bin/nvim ~/bin/nvim
curl -L https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz | tar -xv --strip-components 1 -C "$nightly_dir"
