#!/usr/bin/env bash

set -euo pipefail

set -x

# Remove any leftovers from the old way of doing things.
[[ -L ~/bin/nvim ]] && rm ~/bin/nvim
old_nightly_dir="${XDG_DATA_HOME:-$HOME/.local/share}"/nvim-nightly
[[ -d "$old_nightly_dir" ]] && rm -rf "$old_nightly_dir"

bob_bin_dir="${XDG_DATA_HOME:-$HOME/.local/share}"/bob/nvim-bin

if [[ ! -d "$bob_bin_dir" ]]; then
  bob use nightly
  bob install stable
else
  bob update --all
fi
