#!/usr/bin/env bash
# Set up rbenv for ruby version management.

set -euo pipefail

. "$(dirname "$0")"/../../helpers/setup.sh # Load helper script from dot/helpers.

set -x

changed1=$(gitCloneOrUpdate rbenv/rbenv "$XDG_DATA_HOME/rbenv")
changed2=$(gitCloneOrUpdate rbenv/rbenv-default-gems "$XDG_DATA_HOME/rbenv"/plugins/rbenv-default-gems)

[[ -n $changed1 || -n $changed2 ]] || exit 204 # Run if something changed.

if [[ $USER == gib ]]; then
  (pushd "$XDG_DATA_HOME/rbenv" && src/configure && make -C src)
fi
