#!/bin/bash

set -euo pipefail

[[ $OSTYPE == darwin* ]] || exit 204 # Don't run if not Darwin.

# The fixed string, with touchid added as the second option.
fixed="# sudo: auth account password session
auth       sufficient     pam_smartcard.so
auth       sufficient     pam_tid.so
auth       required       pam_opendirectory.so
account    required       pam_permit.so
password   required       pam_deny.so
session    required       pam_permit.so"

current=$(</etc/pam.d/sudo)

# Skip if /etc/pam.d/sudo is already the fixed version.
[[ "$current" == "$fixed" ]] && exit 204

# What comes in macOS by default.
unchanged="# sudo: auth account password session
auth       sufficient     pam_smartcard.so
auth       required       pam_opendirectory.so
account    required       pam_permit.so
password   required       pam_deny.so
session    required       pam_permit.so"

# Bail out if the contents don't match what we expected to see.
if [[ "$unchanged" != "$current" ]]; then
  echo -e "Error: unexpected contents of /etc/pam.d/sudo:

Actual:
---$current---

Expected:
+++$unchanged+++" >&2
  exit 7
fi

# Insert `auth       sufficient     pam_tid.so` on line 3 of /etc/pam.d/sudo
sudo tee <<<"${fixed}" /etc/pam.d/sudo >/dev/null
