#!/usr/bin/env bash

set -eux

# Check VOLTA_HOME was set (by up).
[[ -n $VOLTA_HOME ]]

# TODO(gib): do we need this if we're installing volta via brew?
curl https://get.volta.sh | bash -s -- --skip-setup
volta install node@lts yarn
