[env]
dot_dir = "~/code/dot" # Directory to clone dotfiles to.
dotfile_dir = "~/code/dot/dotfiles" # Directory to link dotfiles from.
backup_dir = "~/backup" # Directory to move files overwritten by linking.

HOME = "$HOME" # Current user's homedir (~), should be set by OS.
USER = "$USER" # Current user, should be set by OS.
PATH = "$PATH" # TODO: don't pass this through.
TERM = "$TERM" # Set by terminal.
TERMINFO = "$TERMINFO" # Set by terminal.
SSH_AUTH_SOCK = "$SSH_AUTH_SOCK" # Set by ssh agent.

XDG_DATA_HOME = "~/.local/share" # Use default XDG values.
XDG_CACHE_HOME = "~/.cache" # Use default XDG values.
XDG_CONFIG_HOME = "~/.config" # Use default XDG values.

RUSTUP_HOME="$XDG_DATA_HOME/rustup" # Rustup install dir.
CARGO_HOME="$XDG_DATA_HOME/cargo" # Cargo install dir.
GOPATH="~/code/go" # Go install dir.
