[env]
dot_dir = "~/code/dot"
dotfile_dir = "~/code/dot/dotfiles"
backup_dir = "~/backup"
HOME = "$HOME"
USER = "$USER"
PATH = "$PATH"
TERM = "$TERM"
RUSTUP_HOME="$RUSTUP_HOME"
CARGO_HOME="$CARGO_HOME"
