needs_sudo = true # TODO(gib): do this on a more granular basis.

bootstrap_tasks = [
  "link_dotfiles",
  "link_wrk_dotfiles",
  "mac",
  "brew",
]

inherit_env = [
  "HOME", # Current user's homedir (~), should be set by OS.
  "USER", # Current user, should be set by OS.
  "PATH", # TODO: don't pass this through.
  "TERM", # Tells logger what terminal this is.
  "TERMINFO", # If set by terminal, enables nice colouring.
  "SSH_AUTH_SOCK", # Set by ssh agent.
  "HISTFILE", # Used to backup zsh history.
]

[env]
dot_dir="~/code/dot" # Directory to clone dotfiles to.
wrk_dot_dir="~/wrk/me/dotfiles-apple" # Directory to clone work dotfiles to.
backup_dir="~/backup" # Directory to move files overwritten by linking.

dotfile_dir="${dot_dir}/dotfiles" # Directory to link dotfiles from.
wrk_dotfile_dir="${wrk_dot_dir}/dotfiles" # Directory to link work dotfiles from.

XDG_DATA_HOME="~/.local/share" # Use default XDG values.
XDG_CACHE_HOME="~/.cache" # Use default XDG values.
XDG_CONFIG_HOME="~/.config" # Use default XDG values.

_Z_DATA="$XDG_CACHE_HOME/z" # z data file (https://github.com/rupa/z).
RUSTUP_HOME="$XDG_DATA_HOME/rustup" # Rustup install dir.
CARGO_HOME="$XDG_DATA_HOME/cargo" # Cargo install dir.
GOPATH="$HOME/code/go" # Go install dir.
GNUPGHOME="$XDG_DATA_HOME/gnupg" # Gpg install dir.
RBENV_ROOT="$XDG_CACHE_HOME/rbenv" # Set rbenv location.
# Used to backup zsh history.
ZSH_CLOUD_HISTFILE="$HOME/Library/Mobile Documents/com~apple~CloudDocs/Fahns/Gib/zsh/history"
# Desktop and Lockscreen background.
MAC_DESKTOP_BACKGROUND="$HOME/Pictures/desktop.png"
# If local file not present, download from this iCloud path.
MAC_CLOUD_DESKTOP_BACKGROUND="$HOME/Library/Mobile Documents/com~apple~CloudDocs/Fahns/Pictures/desktop.png"
