description: |
  Update Mac App Store apps.
  To autorestart run:
    sudo softwareupdate --install --all --restart

run_if_cmd: ["false"] # TODO(gib): Unskip this.
# run_if_cmd: ["/bin/bash", "-cex", '[[ $(uname) == Darwin ]]']
run_cmd: ["softwareupdate", "--install", "--all"]
