description: |
  Update Mac App Store apps.
  To autorestart run:
    sudo softwareupdate --install --all --restart

run_if_cmd: ["/bin/sh", "-c", "exit 204"] # TODO(gib): Unskip this.
run_cmd: ["softwareupdate", "--install", "--all"]
