needs_sudo: true

# Only run when /var/db/locate.database was modified more than an hour ago.
run_if_cmd: ["${dot_dir}/scripts/run_if/updatedb"]

# You can also have this run automatically in the background once a week by running:
#   sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist
run_cmd: ["/bin/zsh", "-euxc", "sudo -n /usr/libexec/locate.updatedb"]
