# Only run when /var/db/locate.database was modified less than an hour ago.
check_cmd = ["/usr/bin/env", "bash", "-c", "(( ($(date +%s) - $(stat -L -f '%m' /var/db/locate.database)) < (1*60*60) ))"]
run_cmd = ["sudo", "-n", "/usr/libexec/locate.updatedb"]
